### ISSUE TITLE
Sound with offhand shield

### ISSUE THREAD

**Issue by Uzimattyan** [NemoNotFound/NemosFireworkKeybinding#2]
When there are fireworks in the inventory, if you equip the shield offhand and press the “Firework” key, you will hear a continuous “Gear equips” sound.

Minecraft 1.21
Firework Keybinding 1.1.1

**Comment by NemoNotFound** [comment]
Damn, so many bugs 😂
But I can already imagine why this is the case. To make this mod client side only I had to make it work like that:

Firework rocket will be put in the offhand slot, then being consumed and put back to the old slot. If there was another item on the previous slot it will get unequipped and equipped again. Because of this the shield equip sound plays.

I'll take a look after work (or in my lunch break) and check how to improve it. 

Thanks for letting me know!

**Comment by NemoNotFound** [comment]
Okay I need more time. I got a new bug which doesn't make sense to me. I can trigger the fireworks while the main hand is in every slot except the first.

Currently looking into it

**Comment by Uzimattyan** [comment]
Okay, I can wait.

**Comment by NemoNotFound** [comment]
I updated it, please check!

**Comment by Uzimattyan** [comment]
Confirmed.

Thank you again for your courteous response!

**Comment by NemoNotFound** [comment]
Lovely! Thank you for reporting the issue :D
